version: '3.8'

services:
  

  postgres-db:
    image: postgres:latest
    container_name: projeto-integrador-postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    
